# Generated by Django 4.2.7 on 2024-12-24 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_file_encryption_iv_file_encryption_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='encryption_iv',
            field=models.BinaryField(default=b''),
        ),
        migrations.AlterField(
            model_name='file',
            name='encryption_tag',
            field=models.BinaryField(default=b''),
        ),
    ]
