# Generated by Django 4.2.7 on 2024-12-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_alter_file_encryption_iv_alter_file_encryption_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='encryption_iv',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='encryption_key',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
