# Generated by Django 4.2.7 on 2024-12-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_alter_file_encryption_iv_alter_file_encryption_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='encryption_iv',
        ),
        migrations.RemoveField(
            model_name='file',
            name='encryption_tag',
        ),
        migrations.AlterField(
            model_name='file',
            name='checksum',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='encryption_key',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='mime_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
