# Generated by Django 4.2.7 on 2024-12-26 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0007_alter_fileshare_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileshare',
            name='shared_with',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
