# Generated by Django 4.2.7 on 2024-12-27 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0008_fileshare_shared_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='owner_keycloak_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
