# Generated by Django 4.2.7 on 2024-12-27 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0009_file_owner_keycloak_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='owner_keycloak_id',
        ),
    ]
