services:
  frontend:
    build: ./frontend
    ports:
      - "3003:3003"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - frontend.env

  backend:
    build: ./backend
    ports:
      - "3002:3002"
    volumes:
      - ./backend:/app
      - file-storage:/app/storage
      - log-storage:/app/logs
    env_file:
      - backend.env

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.2
    ports:
      - "3001:8080"
      - "3004:9000"
    env_file:
      - keycloak.env
    volumes:
      - ./keycloak/themes/secure-files:/opt/keycloak/themes/secure-files:ro
    depends_on:
      db:
        condition: service_started
    
    command:
      - start-dev
      - --health-enabled=true

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - db.env

  keycloak-init:
    build:
      context: .
      dockerfile: keycloak-init.Dockerfile
    env_file:
      - keycloak-init.env
    depends_on:
      keycloak:
        condition: service_started

volumes:
  postgres_data:
  file-storage:
  log-storage: