services:
  cert-generator:
    build: ./cert-generator
    volumes:
      - ./certs:/certs

  nginx:
    image: nginx:alpine
    ports:
      - "8766:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/ssl:ro
    depends_on:
      - cert-generator

  frontend:
    build: ./frontend
    expose:
      - "3003"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ./frontend/.env
    depends_on:
      - nginx

  backend:
    build: ./backend
    expose:
      - "3002"
    volumes:
      - ./backend:/app
      - file-storage:/app/storage
      - log-storage:/app/logs
    env_file:
      - ./backend/.env
    depends_on:
      - nginx

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.2
    env_file:
      - ./keycloak/.env
    volumes:
      # Mount both themes
      - ./keycloak/themes/secure-files:/opt/keycloak/themes/secure-files:ro
      # Mount the custom MFA provider jar
      - ./target/keycloak-mfa-plugin-1.0-SNAPSHOT.jar:/opt/keycloak/providers/keycloak-mfa-plugin-1.0-SNAPSHOT.jar:ro
    depends_on:
      - nginx
      - db
    command:
      - start-dev

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./db/.env

  keycloak-init:
    build:
      context: ./keycloak-init
    env_file:
      - ./keycloak-init/.env
    depends_on:
      keycloak:
        condition: service_started

  telegram-bot:
    build: ./telegram-bot
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    restart: unless-stopped

volumes:
  ssl-certs:
  postgres_data:
  file-storage:
  log-storage: